dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
before_install:
    - eval "${MATRIX_EVAL}"
    - wget https://github.com/keystone-engine/keystone/archive/master.zip
    - unzip master.zip
    - pushd keystone-master
    - mkdir build
    - cd build
    - ../make-share.sh
    - sudo make install
    - sudo ldconfig
    - popd
    - wget https://github.com/ParkHanbum/capstone/archive/master.zip -O capstone-master.zip
    - unzip capstone-master.zip
    - pushd capstone-master
    - ./make.sh
    - sudo make install
    - pushd bindings/python
    - sudo python setup.py install
    - popd
install:
    - pip install -r requirements.txt
compiler: gcc
language: python
python:
    - "2.7"
script:
    - python -m tests/test
cache:
  - pip
  - $HOME/keystone-master

